#!/bin/bash
# 性能诊断脚本 - 帮助定位视频检测延迟问题

echo "================================"
echo "智能交通系统 - 性能诊断工具"
echo "================================"
echo ""

echo "📊 当前配置检查："
echo "-------------------"
echo "ITS_FRAME_SKIP=${ITS_FRAME_SKIP:-1} (默认=1，处理每一帧)"
echo "ITS_OVERLAY_PUSH_SKIP=${ITS_OVERLAY_PUSH_SKIP:-1} (默认=1，每帧推送overlay)"
echo "ITS_PLATE_RECOGNITION_SKIP=${ITS_PLATE_RECOGNITION_SKIP:-3} (默认=3，每3帧识别一次车牌)"
echo "ITS_VEHICLE_CONF=${ITS_VEHICLE_CONF:-0.50} (车辆检测阈值)"
echo "ITS_PLATE_CONF=${ITS_PLATE_CONF:-0.20} (车牌检测阈值)"
echo ""

echo "🔍 已知性能瓶颈："
echo "-------------------"
echo "1. 车牌识别 (LPRNet): 50-100ms/车牌 - 最耗时"
echo "2. 车辆检测 (YOLO): 30-80ms/帧"
echo "3. 车辆跟踪 (ByteTrack): 5-15ms/帧"
echo "4. 车牌检测 (YOLO): 20-50ms/帧"
echo ""

echo "🎯 推荐优化方案："
echo "-------------------"
echo ""
echo "【方案1：快速修复 - 降低帧率】"
echo "适用：CPU/GPU性能不足，总处理时间>100ms"
echo ""
echo "export ITS_FRAME_SKIP=3          # 每3帧处理1帧（提升3倍速度）"
echo "export ITS_OVERLAY_PUSH_SKIP=1   # 每帧都推送（保持流畅）"
echo ""
echo "效果：降低AI负载，但会略微降低检测连续性"
echo ""

echo "【方案2：跳过车牌识别】"
echo "适用：不需要识别具体车牌号，只需要检测车辆"
echo ""
echo "修改代码：video_processor.py"
echo "将 ITS_PLATE_RECOGNITION_SKIP 设为很大的值（如999）"
echo "或在车牌识别场景外完全跳过"
echo ""

echo "【方案3：降低检测阈值】"
echo "适用：移动车辆检测不到（YOLO置信度不足）"
echo ""
echo "export ITS_VEHICLE_CONF=0.35     # 降低阈值（默认0.50）"
echo ""
echo "风险：可能增加误检"
echo ""

echo "【方案4：优化ByteTrack参数】"
echo "适用：跟踪不稳定，频繁丢失ID"
echo ""
echo "export ITS_TRACKER_MAX_LOST=60        # 增加丢失容忍帧数（默认45）"
echo "export ITS_TRACKER_TRACK_THRESH=0.30  # 降低跟踪阈值（默认0.35）"
echo "export ITS_TRACKER_MATCH_THRESH=0.25  # 降低匹配阈值（默认0.30）"
echo ""

echo ""
echo "🚀 快速启动（推荐配置）："
echo "-------------------"
echo ""
echo "# 高性能模式（如果GPU强劲）"
echo "export ITS_FRAME_SKIP=1"
echo "export ITS_OVERLAY_PUSH_SKIP=1"
echo "export ITS_PLATE_RECOGNITION_SKIP=5"
echo "python3 cloud/stream_receiver/main_server.py"
echo ""
echo "# 平衡模式（推荐，适合大多数场景）"
echo "export ITS_FRAME_SKIP=2"
echo "export ITS_OVERLAY_PUSH_SKIP=1"
echo "export ITS_VEHICLE_CONF=0.40"
echo "python3 cloud/stream_receiver/main_server.py"
echo ""
echo "# 低延迟模式（CPU较弱，优先流畅度）"
echo "export ITS_FRAME_SKIP=3"
echo "export ITS_OVERLAY_PUSH_SKIP=1"
echo "export ITS_PLATE_RECOGNITION_SKIP=999  # 禁用车牌识别"
echo "export ITS_VEHICLE_CONF=0.35"
echo "python3 cloud/stream_receiver/main_server.py"
echo ""

echo "📝 运行后观察日志："
echo "-------------------"
echo "重点查看性能监控报告（每30帧输出一次）："
echo "- 总耗时应 < 100ms（才能支持10fps实时处理）"
echo "- 车牌识别如果>100ms，考虑降低频率或禁用"
echo "- 车辆检测如果>80ms，考虑使用更小的模型"
echo ""
echo "================================"
